on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master

name: makefile build

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v2
        
        - name: build application
          run: make
